#########################
# Gatling Configuration #
#########################

gatling {
  data {
    writers = [console, file, graphite]
    graphite {
      host = "127.0.0.1"
      port = 2003
      protocol = "tcp"
      rootPathPrefix = "gatling"
      writePeriod = 1
    }
  }
}